<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-03-29T13:39:19+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.do_page_reindex_check
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'locale' => 'en_GB',
    'version_installed' => '8.1.0',
    'version_db_installed' => '20170123000000',
    'misc' => [
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1490558954,
        'do_page_reindex_check' => false,
        'latest_version' => '8.1.0',
    ],
    'seo' => [
        'redirect_to_canonical_url' => 0,
        'url_rewriting' => false,
    ],
    'cache' => [
        'blocks' => false,
        'assets' => false,
        'theme_css' => false,
        'overrides' => false,
        'pages' => '0',
        'full_page_lifetime' => 'default',
        'full_page_lifetime_value' => null,
    ],
    'theme' => [
        'compress_preprocessor_output' => false,
        'generate_less_sourcemap' => false,
    ],
    'debug' => [
        'detail' => 'debug',
        'display_errors' => true,
    ],
];
